name: redux_future
description: A Redux Middleware for handling Dart Futures as actions
version: 0.2.0
homepage: https://github.com/brianegan/redux_future
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  redux: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: "^1.0.0"
